### ISSUE TITLE
JLLWrappers for some GR.jl dependencies

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#1979]
As discussed in https://github.com/jheinen/GR.jl/issues/314#issuecomment-715523311, the following JLL packages may benefit from using JLLWrappers. Noting the list here.

- [x] EarCut_jll
- [x] GR_jll (#2204)
- [x] MbedTLS_jll
- [x] Qhull_jll
- [x] Qt_jll (#2123)
- [x] Xorg_xcb_util_image_jll (#2185)
- [x] Xorg_xcb_util_jll (#2185)
- [x] Xorg_xcb_util_keysyms_jll (#2185)
- [x] Xorg_xcb_util_renderutil_jll (#2185)
- [x] Xorg_xcb_util_wm_jll (#2185)
- [x] libpng_jll

I might not have analyzed it correctly. It would be great if someone else could double-check this list.

**Comment by ViralBShah** [comment]
@giordano I am thinking Xorg, EarCut, MbedTLS, and GR may be ok. And QT would not be doable. Is that about right?

**Comment by giordano** [comment]
better not to touch MbedTLS for the time being, we've had too many problems with Julia dependencies in the last days

**Comment by ViralBShah** [comment]
The precompile time seems to have significantly improved. Would be nice if someone else can verify.

https://github.com/jheinen/GR.jl/issues/314#issuecomment-724735997

**Comment by ViralBShah** [comment]
@barche I think `Qt_jll` needs to be rebuilt to use JLLWrappers.

**Comment by ViralBShah** [comment]
@giordano Would all the Xorg stuff need rebuilding to get JLLWrappers for the remaining packages above?

**Comment by giordano** [comment]
I think they all need to get the wrappers updated, yes: https://github.com/JuliaBinaryWrappers?q=Xorg_xcb_util_jll.  However I believe we need to rebuild the tarballs from scratch (so no `[skip build]`) because the current tarballs are using the old name for `armv7` platforms

**Comment by barche** [comment]
> @barche I think `Qt_jll` needs to be rebuilt to use JLLWrappers. I believe your open PR for GR_jll to user the internal Qhull should solve JLLWrappers for GR_jll.

Yes, it created the wrappers in my local test. For Qt: anything else needed while we're at it, such as maybe trying to add more platforms?

**Comment by ViralBShah** [comment]
Do we already have Qt on armv8? Give the full default platform list a try and see if we can do some more? The buildbots are much faster now.

**Comment by barche** [comment]
It is on `armv7l`. Before I start iterating on this using the build bots: is this paid by the CPU hour or something like that? Iterating on Qt for more platforms will likely consume dozens of CPU hours.

**Comment by ViralBShah** [comment]
A lot of the build infrastructure is now on MIT servers operated by Julia Lab. So go for it.

**Comment by terasakisatoshi** [comment]
Would be nice if Qt_jl supports for armv8.

My script is depends on Qt_jll

https://github.com/terasakisatoshi/OpenCVBuilder.jl/blob/main/qt/build_tarball.jl#L45

**Comment by vchuravy** [comment]
> It is on armv7l. Before I start iterating on this using the build bots: is this paid by the CPU hour or something like that? Iterating on Qt for more platforms will likely consume dozens of CPU hours.

Please do! The server is bored and as Viral said it is hosted by us at MIT.

**Comment by barche** [comment]
What is the platform name for armv8, actually?

**Comment by giordano** [comment]
aarch64

**Comment by oschulz** [comment]
Oh, yes, pretty please - I'd love to run (and more importantly, show off) Julia on an ARM 64-bit Chromebook, but Plot + GR is kinda necessary for that ...

**Comment by barche** [comment]
Qt WIP at PR #2123
