### ISSUE TITLE
Meta issue about building packages for experimental platforms (`aarch64-apple-darwin` and `armv6l-linux-*`)

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/Yggdrasil#2763]
There is a large demand to build packages for the "experimental" platforms `aarch64-apple-darwin` and `armv6l-linux-*`, but there are two _**NON-NEGOTIABLE**_ constraints

1. the JLL package _**must require at least Julia v1.6**_, because only Julia v1.6+ is able to deal with the presence of these platforms in the `Artifacts.toml` file
2. most existing packages are marked as compatible with Julia v1.0, but as a consequence of the point 1 above if we want to rebuild an existing package for the new platform the generated JLL package _**must have a new version number**_.  No exceptions whatsoever to this rule, otherwise we'll break the ecosystem for Julia v1.5-

Also, if a package has binary dependencies, we need to build all of them before being able to build it.  The fact that we need to require Julia v1.6 means that we need to cut out of support old versions of Julia, and not all package maintainers will be happy about that decision.  The rebuild of the packages of a consistent part of the ecosystem will reasonably take a few months, certainly not before a new long-term support (LTS) version of Julia is officially announced.

Examples of commonly requested packages:
* [x] FFTW: it doesn't have dependencies, but (a) we need to build a new version (b) the maintainer needs to agree to require Julia v1.6 (https://github.com/JuliaMath/FFTW.jl/issues/168, https://github.com/JuliaMath/FFTW.jl/issues/187, #2738; related to the issue of requiring Julia v1.6: https://github.com/JuliaMath/FFTW.jl/issues/188)
* [x] zeromq (https://github.com/JuliaInterop/ZMQ.jl/issues/210, https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1072; built in #3194)
* [x] openspecfun: no dependencies (#2892)
* [x] Hwloc: no dependencies, but needs to require Julia v1.6 for a new version (https://github.com/JuliaParallel/Hwloc.jl/issues/44, #2733, done in #3190)
* [x] Rmath (asked a few times in https://github.com/JuliaLang/julia/issues/36617 because it's an indirect dependency of `Distributions.jl`): built with #2732
* [x] GR: lots of dependencies (#2760)
* [x] libsodium: done in #2768
* [x] bzip2: #2957
* [x] freetyp2: #2994
* [x] expat: #2995
* [x] libuuid: #2997	
* [x] fontconfig: #2998
* [x] libiconv: #3004
* [x] libmount: #3006
* [x] libffi: #3007
* [x] xml2: #3009
* [x] pcre: #3010
* [x] lz4: #3035
* [x] gettext: #3037
* [x] glib: #91
* [x] lzo: #3047
* [x] pixman: #3048
* [x] libpng: #3049
* [x] libgpg_error: #3050
* [x] libgcrypt: #3056
* [x] xslt: #3055
* [x] ICU: #3068
* [x] cairo: #3062
* [x] graphite2: #3070
* [x] fribidi: #3071
* [x] ncurses: #3075
* [x] harfbuzz: #3069
* [x] pango: #3079
* [x] lame: #3093
* [x] libvpx: #3094
* [x] openssl: #3096
* [x] opus: #3097
* [x] ogg: #3098
* [x] libass: #3100
* [x] libfdk_aac: #3101
* [x] libvorbis: #3102
* [x] x264: #3103
* [x] x265: #3104
* [x] ffmpeg: #3105
* [x] jpegturbo: #3107
* [x] libtiff: #3110
* [x] cuba: #3114
* [x] glfw: #3118
* [x] qt5base: #3119
* [x] libwebp: #3306 
* [x] leptonica: 3308
* [x] littlecms: #3309
* [x] openjpeg: 3310
* [x] graphene: 3393
* [x] libepoxy: #3392
* [x] atk: #3397
* [x] gdk-pixbuf 3398
* [x] gtk3: #3401
* [ ] SymEngine

**Comment by giordano** [comment]
Note: I've built bzip2 for the new architectures with #2957, but that changed the soname of the library, which means we can't have downstream libraries depending on both v1.0.6 and v1.0.8 (registration has been put on hold: https://github.com/JuliaRegistries/General/pull/36391), they _must_ be rebuilt against v1.0.8.

**Comment by mkborregaard** [comment]
This seems to happen for ImageMagick as well
```
julia> using ImageMagick
ERROR: InitError: UndefVarError: libwand not defined
Stacktrace:
 [1] magickgenesis
   @ ~/.julia/packages/ImageMagick/b8swT/src/libmagickwand.jl:21 [inlined]
 [2] __init__()
   @ ImageMagick ~/.julia/packages/ImageMagick/b8swT/src/libmagickwand.jl:27
 [3] _include_from_serialized(path::String, depmods::Vector{Any})
   @ Base ./loading.jl:768
 [4] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
   @ Base ./loading.jl:854
 [5] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1097
 [6] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1013
 [7] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:997
during initialization of module ImageMagick
```
Is this thread the right place to report?

**Comment by giordano** [comment]
> Is this thread the right place to report?

Yes, but there was already a PR open (and already merged a couple of weeks ago) for this: #3424

**Comment by gbaraldi** [comment]
libhdf5 isn't supported on either the M1 and also lots of other platforms :s . But it looks to be really awful to build.

**Comment by giordano** [comment]
We can't cross-compile HDF5, we repackage native builds from the Python ecosystem

**Comment by giordano** [comment]
Uh, sorry, I missed the message. No, probably this can be closed now.
