### ISSUE TITLE
On the road to GTK

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/Yggdrasil#62]
- [x] GTK (PR #85) ([`meson.build`](https://gitlab.gnome.org/GNOME/gtk/blob/3.24.11/meson.build), [`meson_options.txt`](https://gitlab.gnome.org/GNOME/gtk/blob/3.24.11/meson_options.txt); [ArchLinux](https://www.archlinux.org/packages/extra/x86_64/gtk3/),  [HomeBrew](https://formulae.brew.sh/formula/gtk+3), [Linux From Scratch](http://www.linuxfromscratch.org/blfs/view/cvs/x/gtk3.html), [Debian](https://packages.debian.org/source/sid/gtk+3.0), [Spack](https://spack.readthedocs.io/en/latest/package_list.html#gtkplus))
  - [x] glib2
  - [x] gdk-pixbuf (PR #72) ([ArchLinux](https://www.archlinux.org/packages/extra/x86_64/gdk-pixbuf2/), [HomeBrew](https://formulae.brew.sh/formula/gdk-pixbuf), [Linux From Scratch](http://www.linuxfromscratch.org/blfs/view/svn/x/gdk-pixbuf.html), [Debian](https://packages.debian.org/source/sid/gdk-pixbuf), [Spack](https://spack.readthedocs.io/en/latest/package_list.html#gdk-pixbuf))
    - [x] glib2
    - <s>[x] shared-mime-info (PR #61)</s> (not needed when disabling gio-sniffing in gdk-pixbuf)
    - [x] libjpeg-turbo
    - [x] libpng
    - [x] libtiff (PR #58)
    - [x] libx11
    - <s>[ ] jasper</s> (optional)
  - [x] Pango (https://github.com/JuliaPackaging/Yggdrasil/pull/41)
  - [x] rsvg (PR #90) ([ArchLinux](https://www.archlinux.org/packages/extra/x86_64/librsvg/),  [HomeBrew](https://formulae.brew.sh/formula/librsvg), [Linux From Scratch](http://www.linuxfromscratch.org/blfs/view/svn/general/librsvg.html), [Debian](https://packages.debian.org/source/sid/librsvg), [Spack](https://spack.readthedocs.io/en/latest/package_list.html#librsvg))
    - [x] gdk-pixbuf (PR #72)
    - [x] libcroco (PR #57)
    - [x] pango
  - [x] ATK (PR #67)
  - [x] at-spi2-atk (only when X11 is enabled, i.e., Linux and FreeBSD) (PR #148) ([`meson.build`](https://gitlab.gnome.org/GNOME/at-spi2-atk/blob/master/meson.build), [`meson_options.txt`](https://gitlab.gnome.org/GNOME/at-spi2-atk/blob/master/meson_options.txt); [ArchLinux](https://www.archlinux.org/packages/extra/x86_64/at-spi2-atk/), [Linux From Sctratch](http://www.linuxfromscratch.org/blfs/view/cvs/x/at-spi2-atk.html), [Debian](https://packages.debian.org/source/sid/at-spi2-atk), [Spack](https://spack.readthedocs.io/en/latest/package_list.html#at-spi2-atk))
    - [x] at-spi2-core (PR #146) ([`meson.build`](https://gitlab.gnome.org/GNOME/at-spi2-core/blob/master/meson.build), [`meson_options.txt`](https://gitlab.gnome.org/GNOME/at-spi2-core/blob/master/meson_options.txt); [ArchLinux](https://www.archlinux.org/packages/extra/x86_64/at-spi2-core), [Linux From Sctratch](http://www.linuxfromscratch.org/blfs/view/cvs/x/at-spi2-core.html), [Debian](https://packages.debian.org/source/sid/at-spi2-core), [Spack](https://spack.readthedocs.io/en/latest/package_list.html#at-spi2-core))
      - [x] dbus (PR #142)
        - <s>[ ] audit</s>
          - <s>[ ] krb5</s>
            - <s>[ ] e2fsprogs</s>
            - <s>[x] keyutils (PR #112)</s>
            - <s>[ ] libldap</s>
          - <s>[x] libcap-ng (PR #120)</s>
        - <s>[x] expat</s>
        - <s>[ ] systemd-libs</s>
          - <s>[x] libcap (PR #137)</s>
          - <s>[x] libgcrypt (PR #111)</s>
          - <s>[x] lz4 (PR #97)</s>
          - <s>[x] xz</s>
      - [x] libxtst (part of X11)
      - [x] Glib
  - [x] libepoxy (PR #66) ([`meson.build`](https://github.com/anholt/libepoxy/blob/1.5.3/meson.build), [`meson_options.txt`](https://github.com/anholt/libepoxy/blob/1.5.3/meson_options.txt); [ArchLinux](https://www.archlinux.org/packages/extra/x86_64/libepoxy/),  [HomeBrew](https://formulae.brew.sh/formula/libepoxy), [Linux From Scratch](http://www.linuxfromscratch.org/blfs/view/cvs/x/libepoxy.html), [Debian](https://packages.debian.org/source/sid/libepoxy), [Spack](https://spack.readthedocs.io/en/latest/package_list.html#libepoxy))
    - [x] libglvnd (only Linux and FreeBSD) (PR #99) ([ArchLinux](https://www.archlinux.org/packages/extra/x86_64/libglvnd/))
    - [x] x11 (optional)
  - [x] adwaita-icon-theme (PR #68)
    - [x] hicolor-icon-theme (PR #140)
  - [x] Cairo
  - [x] HarfBuzz
  - [x] graphene (PR #77)
  - [x] iso-codes (PR #76)
  - [x] wayland (optional, only for Linux and FreeBSD) (PR #78)
  - [x] wayland-protocols (optional, only for Linux and FreeBSD) (PR #96)
  - [x] xkbcommon (only when wayland is enabled) (PR #147) ([ArchLinux](https://www.archlinux.org/packages/extra/x86_64/libxkbcommon/))
    - [x] xkeyboard-config ([ArchLinux](https://www.archlinux.org/packages/extra/any/xkeyboard-config/))
      - <s>[x] libxslt (PR #115) ([ArchLinux](https://www.archlinux.org/packages/extra/x86_64/libxslt/))</s>
        - <s>[x] libgcrypt (PR #111) ([ArchLinux](https://www.archlinux.org/packages/core/x86_64/libgcrypt/))</s>
          - <s>[x] libgpg-error (PR #108) ([ArchLinux](https://www.archlinux.org/packages/core/x86_64/libgpg-error/))</s>
      - [x] xorg-xkbcomp (PR #141) ([ArchLinux](https://www.archlinux.org/packages/extra/x86_64/xorg-xkbcomp/))
        - [x] libxkbfile (in PR #92) ([ArchLinux](https://www.archlinux.org/packages/extra/x86_64/libxkbfile/))
    - [x] libglvnd
    - [x] libxcb (in X11)
  - who-knows-what-else...

Other packages, depending on GTK, needed for `Gtk.jl`:

- [ ] gnome-themes-extra (PR #113) ([`configure.ac`](https://gitlab.gnome.org/GNOME/gnome-themes-extra/blob/master/configure.ac); [ArchLinux](https://www.archlinux.org/packages/extra/x86_64/gnome-themes-extra/),  [HomeBrew](https://formulae.brew.sh/formula/gnome-themes-standard), [Linux From Scratch](http://www.linuxfromscratch.org/blfs/view/svn/x/gnome-themes-extra.html), [Debian](https://packages.debian.org/source/sid/gnome-themes-extra))
  - [x] GTK3 (PR #85)

Moved from https://github.com/ianshmean/GTK3Builder/issues/1.

**Comment by giordano** [comment]
Note: GTK3 on Windows requires Cairo 1.15.2.  Currently we have the builder for 1.14.12.  I think that Cairo >= 1.15 requires a newer version of Glib2, so we need to fix the issues in #91 for macOS and FreeBSD
