### ISSUE TITLE
jlls without licenses

### ISSUE THREAD

**Issue by aviks** [JuliaPackaging/Yggdrasil#6764]
The following jlls have been released without a license file in the repo. This is quite a problem for tools that perform license checks. 

- ~[ ] xhyve_jll~
- [x] Xorg_compositeproto_jll (#6771)
- [x] Xorg_damageproto_jll (#6771)
- [x] Xorg_dri2proto_jll (#6771)
- [x] Xorg_dri3proto_jll (#6771)
- [x] Xorg_fixesproto_jll (#6771)
- [X] Xorg_randrproto_jll (#6771)
- [X] Xorg_recordproto_jll (#6771)
- [X] Xorg_scrnsaverproto_jll (#6771)
- [X] Xorg_xf86vidmodeproto_jll (#6771)
- [X] Xorg_xineramaproto_jll (#6771)
- ~[ ] X11_jll~
- [x] TVM_jll (#6773)
- ~[ ] Patchelf_jll~
- [X] PATHlib_jll #6772
- [X] lm_Sensors_jll #6772
- [x] libmodplug_jll (#6773)
- [X] Keyutils_jll #6772

**Comment by giordano** [comment]
Note that `X11_jll` is an _old_ package, I'm not inclined to rebuild it.  No one should be using nowadays.

**Comment by giordano** [comment]
Also, xhyve [isn't anywhere in this repository](https://github.com/search?q=repo%3AJuliaPackaging%2FYggdrasil%20xhyve&type=code), I guess you'll have to ask @staticfloat where that comes from.

**Comment by giordano** [comment]
Another note: all `Xorg_*proto_jll` packages are headers-only and no Julia package should depend on them, if you found such cases we should rectify them because that'd be wrong.

**Comment by giordano** [comment]
Also, the artifact of patchelf _does_ have a license file as far as I can tell, see for example https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl/releases/download/Patchelf-v0.17.2%2B0/Patchelf.v0.17.2.x86_64-linux-gnu-cxx11.tar.gz.  How did you get that list?

**Comment by aviks** [comment]
> Also, the artifact of patchelf does have a license file as far as I can tell, see for example

Sorry if it wasn't clear, I just checked the license on the jll sources. There are likely other packages without licenses in the artifacts, that check if for another day. 

Thanks for fixing these.
